AllCops:
  Exclude:
    - bin/*
  TargetRubyVersion: 2.5

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/*
    - '*.gemspec'

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
